server:
  port: 9000
spring:
  kafka:
    #bootstrap-servers: lxieslt2.transplace.com:9092
    #bootstrap-servers: pkc-epgnk.us-central1.gcp.confluent.cloud:9092
    bootstrap-servers: lxapocd1.transplace.com:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      topic: test.t
  #  properties:
  #    ssl.endpoint.identification.algorithm: https
  #    sasl.mechanism: PLAIN
  #    request.timeout.ms: 20000
  #    retry.backoff.ms: 500
  #    sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="PLKGVB5PA7QKXPFX" password="URVyZz/bD8PEjYn6/P/zlbjjvySpkSnGRBei7KiTRjDw4Jm0t8SSe9ekaAZ1tmSp";
  #    security.protocol: SASL_SSL
